/*
 * This file is generated by jOOQ.
 */
package com.example.phone_info.tables;


import com.example.phone_info.Indexes;
import com.example.phone_info.Keys;
import com.example.phone_info.PhoneInfo;
import com.example.phone_info.tables.records.DataRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Data extends TableImpl<DataRecord> {

    private static final long serialVersionUID = 404698246;

    /**
     * The reference instance of <code>phone_info.data</code>
     */
    public static final Data DATA = new Data();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataRecord> getRecordType() {
        return DataRecord.class;
    }

    /**
     * The column <code>phone_info.data.id</code>.
     */
    public final TableField<DataRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>phone_info.data.party_account</code>.
     */
    public final TableField<DataRecord, String> PARTY_ACCOUNT = createField(DSL.name("party_account"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.access_date</code>.
     */
    public final TableField<DataRecord, String> ACCESS_DATE = createField(DSL.name("access_date"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.response_date</code>.
     */
    public final TableField<DataRecord, String> RESPONSE_DATE = createField(DSL.name("response_date"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.log_type</code>.
     */
    public final TableField<DataRecord, String> LOG_TYPE = createField(DSL.name("log_type"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.app_id</code>.
     */
    public final TableField<DataRecord, String> APP_ID = createField(DSL.name("app_id"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.menu_id</code>.
     */
    public final TableField<DataRecord, String> MENU_ID = createField(DSL.name("menu_id"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.menu_name</code>.
     */
    public final TableField<DataRecord, String> MENU_NAME = createField(DSL.name("menu_name"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.phone_info</code>.
     */
    public final TableField<DataRecord, String> PHONE_INFO = createField(DSL.name("phone_info"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.phone_unique</code>.
     */
    public final TableField<DataRecord, String> PHONE_UNIQUE = createField(DSL.name("phone_unique"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>phone_info.data.error_msg</code>.
     */
    public final TableField<DataRecord, String> ERROR_MSG = createField(DSL.name("error_msg"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>phone_info.data</code> table reference
     */
    public Data() {
        this(DSL.name("data"), null);
    }

    /**
     * Create an aliased <code>phone_info.data</code> table reference
     */
    public Data(String alias) {
        this(DSL.name(alias), DATA);
    }

    /**
     * Create an aliased <code>phone_info.data</code> table reference
     */
    public Data(Name alias) {
        this(alias, DATA);
    }

    private Data(Name alias, Table<DataRecord> aliased) {
        this(alias, aliased, null);
    }

    private Data(Name alias, Table<DataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Data(Table<O> child, ForeignKey<O, DataRecord> key) {
        super(child, key, DATA);
    }

    @Override
    public Schema getSchema() {
        return PhoneInfo.PHONE_INFO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATA_PRIMARY);
    }

    @Override
    public Identity<DataRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DATA;
    }

    @Override
    public UniqueKey<DataRecord> getPrimaryKey() {
        return Keys.KEY_DATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<DataRecord>> getKeys() {
        return Arrays.<UniqueKey<DataRecord>>asList(Keys.KEY_DATA_PRIMARY);
    }

    @Override
    public Data as(String alias) {
        return new Data(DSL.name(alias), this);
    }

    @Override
    public Data as(Name alias) {
        return new Data(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Data rename(String name) {
        return new Data(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Data rename(Name name) {
        return new Data(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
