/*
 * This file is generated by jOOQ.
 */
package com.example.phone_info;


import com.example.phone_info.tables.Data;
import com.example.phone_info.tables.records.DataRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>phone_info</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DataRecord, Integer> IDENTITY_DATA = Identities0.IDENTITY_DATA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DataRecord> KEY_DATA_PRIMARY = UniqueKeys0.KEY_DATA_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DataRecord, Integer> IDENTITY_DATA = Internal.createIdentity(Data.DATA, Data.DATA.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DataRecord> KEY_DATA_PRIMARY = Internal.createUniqueKey(Data.DATA, "KEY_data_PRIMARY", Data.DATA.ID);
    }
}
