/*
 * This file is generated by jOOQ.
 */
package com.example.phone_info;


import com.example.phone_info.tables.Data;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in phone_info
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>phone_info.data</code>.
     */
    public static final Data DATA = Data.DATA;
}
