server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    request-context-attribute: req  #req访问request
    allow-request-override: false
    suffix: .html  #后缀名
    content-type: text/html
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ftl
    check-template-location: true
    expose-session-attributes: false
    expose-request-attributes: false
    charset: UTF-8 #编码格式
    order: 1
  mvc:
    static-path-pattern: /static/**