/*
 * This file is generated by jOOQ.
 */
package com.example.phone_info.tables.records;


import com.example.phone_info.tables.Data;
import com.example.phone_info.tables.interfaces.IData;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataRecord extends UpdatableRecordImpl<DataRecord> implements Record11<Integer, String, String, String, String, String, String, String, String, String, String>, IData {

    private static final long serialVersionUID = 1298214326;

    /**
     * Setter for <code>phone_info.data.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>phone_info.data.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>phone_info.data.party_account</code>.
     */
    @Override
    public void setPartyAccount(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>phone_info.data.party_account</code>.
     */
    @Override
    public String getPartyAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>phone_info.data.access_date</code>.
     */
    @Override
    public void setAccessDate(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>phone_info.data.access_date</code>.
     */
    @Override
    public String getAccessDate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>phone_info.data.response_date</code>.
     */
    @Override
    public void setResponseDate(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>phone_info.data.response_date</code>.
     */
    @Override
    public String getResponseDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>phone_info.data.log_type</code>.
     */
    @Override
    public void setLogType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>phone_info.data.log_type</code>.
     */
    @Override
    public String getLogType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>phone_info.data.app_id</code>.
     */
    @Override
    public void setAppId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>phone_info.data.app_id</code>.
     */
    @Override
    public String getAppId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>phone_info.data.menu_id</code>.
     */
    @Override
    public void setMenuId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>phone_info.data.menu_id</code>.
     */
    @Override
    public String getMenuId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>phone_info.data.menu_name</code>.
     */
    @Override
    public void setMenuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>phone_info.data.menu_name</code>.
     */
    @Override
    public String getMenuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>phone_info.data.phone_info</code>.
     */
    @Override
    public void setPhoneInfo(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>phone_info.data.phone_info</code>.
     */
    @Override
    public String getPhoneInfo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>phone_info.data.phone_unique</code>.
     */
    @Override
    public void setPhoneUnique(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>phone_info.data.phone_unique</code>.
     */
    @Override
    public String getPhoneUnique() {
        return (String) get(9);
    }

    /**
     * Setter for <code>phone_info.data.error_msg</code>.
     */
    @Override
    public void setErrorMsg(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>phone_info.data.error_msg</code>.
     */
    @Override
    public String getErrorMsg() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Data.DATA.ID;
    }

    @Override
    public Field<String> field2() {
        return Data.DATA.PARTY_ACCOUNT;
    }

    @Override
    public Field<String> field3() {
        return Data.DATA.ACCESS_DATE;
    }

    @Override
    public Field<String> field4() {
        return Data.DATA.RESPONSE_DATE;
    }

    @Override
    public Field<String> field5() {
        return Data.DATA.LOG_TYPE;
    }

    @Override
    public Field<String> field6() {
        return Data.DATA.APP_ID;
    }

    @Override
    public Field<String> field7() {
        return Data.DATA.MENU_ID;
    }

    @Override
    public Field<String> field8() {
        return Data.DATA.MENU_NAME;
    }

    @Override
    public Field<String> field9() {
        return Data.DATA.PHONE_INFO;
    }

    @Override
    public Field<String> field10() {
        return Data.DATA.PHONE_UNIQUE;
    }

    @Override
    public Field<String> field11() {
        return Data.DATA.ERROR_MSG;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPartyAccount();
    }

    @Override
    public String component3() {
        return getAccessDate();
    }

    @Override
    public String component4() {
        return getResponseDate();
    }

    @Override
    public String component5() {
        return getLogType();
    }

    @Override
    public String component6() {
        return getAppId();
    }

    @Override
    public String component7() {
        return getMenuId();
    }

    @Override
    public String component8() {
        return getMenuName();
    }

    @Override
    public String component9() {
        return getPhoneInfo();
    }

    @Override
    public String component10() {
        return getPhoneUnique();
    }

    @Override
    public String component11() {
        return getErrorMsg();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPartyAccount();
    }

    @Override
    public String value3() {
        return getAccessDate();
    }

    @Override
    public String value4() {
        return getResponseDate();
    }

    @Override
    public String value5() {
        return getLogType();
    }

    @Override
    public String value6() {
        return getAppId();
    }

    @Override
    public String value7() {
        return getMenuId();
    }

    @Override
    public String value8() {
        return getMenuName();
    }

    @Override
    public String value9() {
        return getPhoneInfo();
    }

    @Override
    public String value10() {
        return getPhoneUnique();
    }

    @Override
    public String value11() {
        return getErrorMsg();
    }

    @Override
    public DataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DataRecord value2(String value) {
        setPartyAccount(value);
        return this;
    }

    @Override
    public DataRecord value3(String value) {
        setAccessDate(value);
        return this;
    }

    @Override
    public DataRecord value4(String value) {
        setResponseDate(value);
        return this;
    }

    @Override
    public DataRecord value5(String value) {
        setLogType(value);
        return this;
    }

    @Override
    public DataRecord value6(String value) {
        setAppId(value);
        return this;
    }

    @Override
    public DataRecord value7(String value) {
        setMenuId(value);
        return this;
    }

    @Override
    public DataRecord value8(String value) {
        setMenuName(value);
        return this;
    }

    @Override
    public DataRecord value9(String value) {
        setPhoneInfo(value);
        return this;
    }

    @Override
    public DataRecord value10(String value) {
        setPhoneUnique(value);
        return this;
    }

    @Override
    public DataRecord value11(String value) {
        setErrorMsg(value);
        return this;
    }

    @Override
    public DataRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IData from) {
        setId(from.getId());
        setPartyAccount(from.getPartyAccount());
        setAccessDate(from.getAccessDate());
        setResponseDate(from.getResponseDate());
        setLogType(from.getLogType());
        setAppId(from.getAppId());
        setMenuId(from.getMenuId());
        setMenuName(from.getMenuName());
        setPhoneInfo(from.getPhoneInfo());
        setPhoneUnique(from.getPhoneUnique());
        setErrorMsg(from.getErrorMsg());
    }

    @Override
    public <E extends IData> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataRecord
     */
    public DataRecord() {
        super(Data.DATA);
    }

    /**
     * Create a detached, initialised DataRecord
     */
    public DataRecord(Integer id, String partyAccount, String accessDate, String responseDate, String logType, String appId, String menuId, String menuName, String phoneInfo, String phoneUnique, String errorMsg) {
        super(Data.DATA);

        set(0, id);
        set(1, partyAccount);
        set(2, accessDate);
        set(3, responseDate);
        set(4, logType);
        set(5, appId);
        set(6, menuId);
        set(7, menuName);
        set(8, phoneInfo);
        set(9, phoneUnique);
        set(10, errorMsg);
    }
}
