/*
 * This file is generated by jOOQ.
 */
package com.example.phone_info.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IData extends Serializable {

    /**
     * Setter for <code>phone_info.data.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>phone_info.data.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>phone_info.data.party_account</code>.
     */
    public void setPartyAccount(String value);

    /**
     * Getter for <code>phone_info.data.party_account</code>.
     */
    public String getPartyAccount();

    /**
     * Setter for <code>phone_info.data.access_date</code>.
     */
    public void setAccessDate(String value);

    /**
     * Getter for <code>phone_info.data.access_date</code>.
     */
    public String getAccessDate();

    /**
     * Setter for <code>phone_info.data.response_date</code>.
     */
    public void setResponseDate(String value);

    /**
     * Getter for <code>phone_info.data.response_date</code>.
     */
    public String getResponseDate();

    /**
     * Setter for <code>phone_info.data.log_type</code>.
     */
    public void setLogType(String value);

    /**
     * Getter for <code>phone_info.data.log_type</code>.
     */
    public String getLogType();

    /**
     * Setter for <code>phone_info.data.app_id</code>.
     */
    public void setAppId(String value);

    /**
     * Getter for <code>phone_info.data.app_id</code>.
     */
    public String getAppId();

    /**
     * Setter for <code>phone_info.data.menu_id</code>.
     */
    public void setMenuId(String value);

    /**
     * Getter for <code>phone_info.data.menu_id</code>.
     */
    public String getMenuId();

    /**
     * Setter for <code>phone_info.data.menu_name</code>.
     */
    public void setMenuName(String value);

    /**
     * Getter for <code>phone_info.data.menu_name</code>.
     */
    public String getMenuName();

    /**
     * Setter for <code>phone_info.data.phone_info</code>.
     */
    public void setPhoneInfo(String value);

    /**
     * Getter for <code>phone_info.data.phone_info</code>.
     */
    public String getPhoneInfo();

    /**
     * Setter for <code>phone_info.data.phone_unique</code>.
     */
    public void setPhoneUnique(String value);

    /**
     * Getter for <code>phone_info.data.phone_unique</code>.
     */
    public String getPhoneUnique();

    /**
     * Setter for <code>phone_info.data.error_msg</code>.
     */
    public void setErrorMsg(String value);

    /**
     * Getter for <code>phone_info.data.error_msg</code>.
     */
    public String getErrorMsg();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IData
     */
    public void from(com.example.phone_info.tables.interfaces.IData from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IData
     */
    public <E extends com.example.phone_info.tables.interfaces.IData> E into(E into);
}
